### ISSUE TITLE
set up your Kanban board

### ISSUE THREAD

**Issue by sonyco-4u** [sonyco-4u/Recipe-app#9]
In this project, we created a Kanban board for Ruby capstone project for Module 5.
 
We are two collaborators working on this project;
1. [Kelvin-Ben](https://github.com/Kelvin-Ben)
2. [sonyco-4u](https://github.com/sonyco-4u)

The  Kanban board link to our project can be accessed through this link  [Recipe-app](https://github.com/users/sonyco-4u/projects/14/views/1?layout=board)

**Comment by BenMukebo** [comment]
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @sonyco-4u, @Kelvin-Ben** 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 
- The GitHub issues provide link to their GitHub project. ✔️  
- The GitHub issues provide linformation about the number of people in their group. ✔️  
- All cards are assigned to team members :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
